const SUPABASE_URL = 'https://gpafllxpvxgvdhcnbtez.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwYWZsbHhwdnhndmRoY25idGV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMzkwMzksImV4cCI6MjA4NzcxNTAzOX0.bz4nw21iP8wuUixKfm4ff41OU71yqW5UREurSgZ9LiI';
var supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
